export const products = [
  {
    title: "Camiseta Titular",
    price: 15000,
    stock: 4,
    description: "Camiseta Titular Oficial del C.S.P.B",
    category: "futbol",
    img: "https://res.cloudinary.com/dqpkwwzdz/image/upload/v1688429516/Brillant%C3%A9/Futbol1_v02i6v.jpg",
  },
  {
    title: "Camiseta Alternativa",
    price: 15000,
    stock: 10,
    description: "Camiseta Visitante Oficial del C.S.P.B",
    category: "futbol",
    img: "https://res.cloudinary.com/dqpkwwzdz/image/upload/v1688429516/Brillant%C3%A9/Futbol2_vve2dd.jpg",
  },
  {
    title: "Camiseta Arquero",
    price: 10000,
    stock: 2,
    description: "Camiseta Arquero Titular Oficial del C.S.P.Bn",
    category: "futbol",
    img: "https://res.cloudinary.com/dqpkwwzdz/image/upload/v1688429517/Brillant%C3%A9/Futbol3_hfeowh.jpg",
  },
  {
    title: "Titular Conmemorativa",
    price: 20000,
    stock: 7,
    description: "Camiseta Conmemotaiva por los 100 años del C.S.P.B",
    category: "conmemorativa",
    img: "https://res.cloudinary.com/dqpkwwzdz/image/upload/v1688429516/Brillant%C3%A9/conmemorativa3_h7utuj.jpg",
  },
  {
    title: "Alternativa Conmemorativa",
    price: 20000,
    stock: 8,
    description: "Camiseta Conmemotaiva Visitante por los 100 años del C.S.P.B",
    category: "conmemorativa",
    img: "https://res.cloudinary.com/dqpkwwzdz/image/upload/v1688429516/Brillant%C3%A9/conmemorativa2_po4ars.jpg",
  },
  {
    title: "Conmemorativa Futbol Champagne",
    price: 25000,
    stock: 6,
    description: "Así es el estilo cahmpagne",
    category: "conmemorativa",
    img: "https://res.cloudinary.com/dqpkwwzdz/image/upload/v1688429516/Brillant%C3%A9/conmemorativa1_rovasl.jpg",
  },
];
