export const products = [
  {
    title: "Camiseta Titular",
    price: 15000,
    stock: 4,
    description: "desc",
    category: "futbol",
    img: "https://res.cloudinary.com/dqpkwwzdz/image/upload/v1688429516/Brillant%C3%A9/Futbol1_v02i6v.jpg",
  },
  {
    title: "Camiseta Alternativa",
    price: 15000,
    stock: 10,
    description: "descripción",
    category: "futbol",
    img: "https://res.cloudinary.com/dqpkwwzdz/image/upload/v1688429516/Brillant%C3%A9/Futbol2_vve2dd.jpg",
  },
  {
    title: "Camiseta Arquero",
    price: 10000,
    stock: 2,
    description: "descripción",
    category: "futbol",
    img: "https://res.cloudinary.com/dqpkwwzdz/image/upload/v1688429517/Brillant%C3%A9/Futbol3_hfeowh.jpg",
  },
  {
    title: "Titular Conmemorativa",
    price: 20000,
    stock: 7,
    description: "descripción",
    category: "conmemorativa",
    img: "https://res.cloudinary.com/dqpkwwzdz/image/upload/v1688429516/Brillant%C3%A9/conmemorativa3_h7utuj.jpg",
  },
  {
    title: "Alternativa Conmemorativa",
    price: 20000,
    stock: 8,
    description: "descripción",
    category: "conmemorativa",
    img: "https://res.cloudinary.com/dqpkwwzdz/image/upload/v1688429516/Brillant%C3%A9/conmemorativa2_po4ars.jpg",
  },
  {
    title: "Conmemorativa Futbol Champagne",
    price: 25000,
    stock: 6,
    description: "futbolsda",
    category: "conmemorativa",
    img: "https://res.cloudinary.com/dqpkwwzdz/image/upload/v1688429516/Brillant%C3%A9/conmemorativa1_rovasl.jpg",
  },
];
